//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inter_New_App_Joins.DbConnection
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NewSchoolDb290722Entities1 : DbContext
    {
        public NewSchoolDb290722Entities1()
            : base("name=NewSchoolDb290722Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Marks> tbl_Marks { get; set; }
        public virtual DbSet<tbl_Student> tbl_Student { get; set; }
        public virtual DbSet<tbl_Teacher> tbl_Teacher { get; set; }
        public virtual DbSet<tbl_TeacherSalary> tbl_TeacherSalary { get; set; }
        public virtual DbSet<tbl_UserInfo> tbl_UserInfo { get; set; }
    
        public virtual int sp_AddStudent(Nullable<int> stu_Id, string name, string email, string standard, string address)
        {
            var stu_IdParameter = stu_Id.HasValue ?
                new ObjectParameter("Stu_Id", stu_Id) :
                new ObjectParameter("Stu_Id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var standardParameter = standard != null ?
                new ObjectParameter("Standard", standard) :
                new ObjectParameter("Standard", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AddStudent", stu_IdParameter, nameParameter, emailParameter, standardParameter, addressParameter);
        }
    
        public virtual ObjectResult<sp_SearchStudent_Result> sp_SearchStudent(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SearchStudent_Result>("sp_SearchStudent", idParameter);
        }
    
        public virtual ObjectResult<sp_SelectAll_Student_Result> sp_SelectAll_Student()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SelectAll_Student_Result>("sp_SelectAll_Student");
        }
    
        public virtual ObjectResult<sp_StuMarks_Result> sp_StuMarks()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_StuMarks_Result>("sp_StuMarks");
        }
    
        public virtual ObjectResult<sp_TeacherSalary_Result> sp_TeacherSalary()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TeacherSalary_Result>("sp_TeacherSalary");
        }
    }
}
