//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inter_New_App_Joins.DbConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TeacherSalary
    {
        public int TS_Id { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<int> Teacher_Id { get; set; }
    
        public virtual tbl_Teacher tbl_Teacher { get; set; }
    }
}
