//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inter_New_App_Joins.DbConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Student()
        {
            this.tbl_Marks = new HashSet<tbl_Marks>();
        }
    
        public int Stu_Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Standard { get; set; }
        public string Address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Marks> tbl_Marks { get; set; }
    }
}
